import { useState } from "react"

const METHOD_COLOR = {
  GET:    { bg: "#dcfce7", text: "#166534" },
  POST:   { bg: "#dbeafe", text: "#1e40af" },
  PUT:    { bg: "#fef9c3", text: "#854d0e" },
  DELETE: { bg: "#fee2e2", text: "#991b1b" },
  PATCH:  { bg: "#f3e8ff", text: "#6b21a8" },
}

function ParamTable({ params }) {
  if (!params || params.length === 0) return null
  return (
    <div style={{ marginBottom: 16 }}>
      <p style={s.sectionLabel}>Parameters</p>
      <table style={s.table}>
        <thead>
          <tr>
            {["Name","Type","Location","Required","Default"].map(h => (
              <th key={h} style={s.th}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {params.map((p, i) => (
            <tr key={i} style={{ background: i % 2 === 0 ? "#fafafa" : "white" }}>
              <td style={{...s.td, fontFamily:"monospace", fontWeight:500}}>{p.name}</td>
              <td style={{...s.td, color:"#7c3aed", fontFamily:"monospace"}}>{p.type}</td>
              <td style={s.td}><span style={locationBadge(p.location)}>{p.location}</span></td>
              <td style={s.td}>{p.required ? "✓" : "—"}</td>
              <td style={{...s.td, fontFamily:"monospace", color:"#666"}}>{p.default || "—"}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function locationBadge(loc) {
  const colors = { path: ["#fef3c7","#92400e"], query: ["#dbeafe","#1e40af"], body: ["#f3e8ff","#6b21a8"] }
  const [bg, color] = colors[loc] || ["#f3f4f6","#374151"]
  return { background: bg, color, fontSize: 11, fontWeight: 500, padding: "2px 7px", borderRadius: 20 }
}

function CurlBlock({ curl }) {
  const [copied, setCopied] = useState(false)
  function copy() {
    navigator.clipboard.writeText(curl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }
  return (
    <div style={{ marginBottom: 16 }}>
      <p style={s.sectionLabel}>Curl command</p>
      <div style={s.curlBox}>
        <pre style={s.curlPre}>{curl}</pre>
        <button onClick={copy} style={s.copyBtn}>{copied ? "Copied!" : "Copy"}</button>
      </div>
    </div>
  )
}

function EndpointCard({ route }) {
  const [open, setOpen] = useState(false)
  const mc = METHOD_COLOR[route.method] || { bg: "#f3f4f6", text: "#374151" }
  return (
    <div style={s.card}>
      <div onClick={() => setOpen(!open)} style={s.cardHeader}>
        <span style={{...s.methodBadge, background: mc.bg, color: mc.text}}>
          {route.method}
        </span>
        <code style={s.path}>{route.path}</code>
        {route.description && (
          <span style={s.shortDesc}>{route.description.split(".")[0]}</span>
        )}
        <span style={{marginLeft:"auto", color:"#999", fontSize:12}}>{open?"▲":"▼"}</span>
      </div>

      {open && (
        <div style={s.cardBody}>
          {route.description && (
            <p style={s.description}>{route.description}</p>
          )}
          <ParamTable params={route.params} />
          <CurlBlock curl={route.curl} />
          <div style={{ fontSize: 12, color: "#999" }}>
            Function: <code style={{fontFamily:"monospace"}}>{route.function}</code>
            {route.return_type !== "any" && (
              <span> · Returns: <code style={{fontFamily:"monospace",color:"#7c3aed"}}>{route.return_type}</code></span>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

export default function DocsView({ routes, onBack }) {
  const [search, setSearch] = useState("")
  const [filter, setFilter] = useState("ALL")
  const methods = ["ALL", ...new Set(routes.map(r => r.method))]

  const filtered = routes.filter(r => {
    const matchSearch = r.path.toLowerCase().includes(search.toLowerCase()) ||
      (r.description || "").toLowerCase().includes(search.toLowerCase())
    const matchMethod = filter === "ALL" || r.method === filter
    return matchSearch && matchMethod
  })

  function exportMarkdown() {
    let md = "# API Documentation\n\n"
    md += `> Generated by DocForge — ${routes.length} endpoints\n\n`
    routes.forEach(r => {
      md += `## ${r.method} \`${r.path}\`\n\n`
      if (r.description) md += `${r.description}\n\n`
      if (r.params?.length) {
        md += "### Parameters\n\n| Name | Type | Location | Required |\n|------|------|----------|----------|\n"
        r.params.forEach(p => {
          md += `| \`${p.name}\` | \`${p.type}\` | ${p.location} | ${p.required ? "Yes" : "No"} |\n`
        })
        md += "\n"
      }
      if (r.curl) md += `### Curl\n\n\`\`\`bash\n${r.curl}\n\`\`\`\n\n`
      md += "---\n\n"
    })
    const blob = new Blob([md], { type: "text/markdown" })
    const a = document.createElement("a")
    a.href = URL.createObjectURL(blob)
    a.download = "api-docs.md"
    a.click()
  }

  return (
    <div style={s.page}>
      <div style={s.topBar}>
        <div>
          <h1 style={s.h1}>API Documentation</h1>
          <p style={s.h1Sub}>{routes.length} endpoints</p>
        </div>
        <div style={s.topActions}>
          <button onClick={exportMarkdown} style={s.outlineBtn}>Export .md</button>
          <button onClick={onBack} style={s.outlineBtn}>← New file</button>
        </div>
      </div>

      <div style={s.controls}>
        <input
          placeholder="Search by path or description..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          style={s.searchInput}
        />
        <div style={s.filterRow}>
          {methods.map(m => (
            <button key={m} onClick={() => setFilter(m)}
              style={{...s.filterBtn, background: filter===m?"#111":"white", color: filter===m?"white":"#555", borderColor: filter===m?"#111":"#ddd"}}>
              {m}
            </button>
          ))}
        </div>
      </div>

      {filtered.length === 0 && (
        <p style={{textAlign:"center",color:"#999",marginTop:40}}>No endpoints match your search.</p>
      )}

      {filtered.map((r, i) => <EndpointCard key={i} route={r} />)}
    </div>
  )
}

const s = {
  page:        { maxWidth: 760, margin: "0 auto", padding: "32px 20px", fontFamily: "-apple-system, sans-serif" },
  topBar:      { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24, flexWrap: "wrap", gap: 12 },
  h1:          { fontSize: 22, fontWeight: 600, color: "#111", marginBottom: 2 },
  h1Sub:       { fontSize: 13, color: "#888" },
  topActions:  { display: "flex", gap: 8 },
  outlineBtn:  { padding: "7px 14px", background: "white", border: "1px solid #ddd", borderRadius: 8, cursor: "pointer", fontSize: 13, color: "#333" },
  controls:    { marginBottom: 20 },
  searchInput: { width: "100%", padding: "10px 14px", border: "1px solid #e5e7eb", borderRadius: 8, fontSize: 14, marginBottom: 12, outline: "none" },
  filterRow:   { display: "flex", gap: 6, flexWrap: "wrap" },
  filterBtn:   { padding: "5px 12px", border: "1px solid", borderRadius: 20, cursor: "pointer", fontSize: 12, fontWeight: 500, transition: "all 0.15s" },
  card:        { border: "1px solid #e5e7eb", borderRadius: 10, marginBottom: 10, overflow: "hidden", background: "white" },
  cardHeader:  { display: "flex", alignItems: "center", gap: 10, padding: "13px 16px", cursor: "pointer", flexWrap: "wrap" },
  methodBadge: { fontSize: 11, fontWeight: 700, padding: "3px 8px", borderRadius: 5, minWidth: 56, textAlign: "center", flexShrink: 0 },
  path:        { fontSize: 14, fontFamily: "monospace", color: "#111", fontWeight: 500 },
  shortDesc:   { fontSize: 12, color: "#888", flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  cardBody:    { padding: "16px", borderTop: "1px solid #f3f4f6", background: "#fafafa" },
  description: { fontSize: 14, color: "#444", marginBottom: 16, lineHeight: 1.6 },
  sectionLabel:{ fontSize: 11, fontWeight: 600, color: "#888", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 8 },
  table:       { width: "100%", borderCollapse: "collapse", fontSize: 13, border: "1px solid #e5e7eb", borderRadius: 6, overflow: "hidden", marginBottom: 0 },
  th:          { padding: "8px 12px", background: "#f9fafb", color: "#555", fontWeight: 500, textAlign: "left", borderBottom: "1px solid #e5e7eb", fontSize: 12 },
  td:          { padding: "8px 12px", borderBottom: "1px solid #f3f4f6", color: "#333" },
  curlBox:     { display: "flex", gap: 8, alignItems: "flex-start" },
  curlPre:     { flex: 1, background: "#1a1a1a", color: "#e5e5e5", padding: "12px 14px", borderRadius: 8, fontSize: 12, fontFamily: "monospace", overflow: "auto", margin: 0, lineHeight: 1.6 },
  copyBtn:     { padding: "8px 14px", background: "#111", color: "white", border: "none", borderRadius: 6, cursor: "pointer", fontSize: 12, whiteSpace: "nowrap", flexShrink: 0 },
}